variables:
  IMAGE_COMMIT: $CI_REGISTRY_IMAGE/commit:$CI_COMMIT_SHA

include:
  - project: jeff_cook/policy
    ref: v0.1.0
    file: /.gitlab-ci/.gitlab-ci.yml
  - project: jeff_cook/policy
    ref: v0.1.0
    file: /docker_build/.gitlab-ci.yml

stages:
  - debug
  - pre_build
  - build
  - post_build
  - test
  - pre_deliver
  - deliver
  - post_deliver
  - pre_deploy
  - deploy
  - post_deploy

# debug:
#   stage: debug
#   services:
#     - docker:stable-dind
#   image: docker:stable
#   script:
#     - env
#     - docker info

verify_image:
  stage: post_build
  image:
    name: $IMAGE_COMMIT
    entrypoint: [""]
  script:
    - yamllint --version
    - yamllint --help
