variables:
  ENABLE_YAMLLINT: 'true'

stages: 
  - pre_build

yamllint:
  stage: pre_build
  rules:
    - exists:
        - '**.yaml'
        - '**.yml'
  only:
    variables:
      - $ENABLE_YAMLLINT == 'true'       
  image: registry.gitlab.com/jeff_cook/yamllint
  script:
    - yamllint -f parsable .
