variables:
  ENABLE_YAMLLINT: 'true'

stages: 
  - pre_build

yamllint:
  stage: pre_build
  rules:
    - exists:
        - '**.yaml'
        - '**.yml'
  image: registry.gitlab.com/jeff_cook/yamllint
  script:
    - '[ "$ENABLE_YAMLLINT" == "true" ] || yamllint -f parsable .'
